name: pinball-rocm-strict
dependencies:
  - python >= 3.14.4
  - pip == 26.0.1
  - pip:
    - --index-url https://download.pytorch.org/whl/rocm7.2
    - torch == 2.11.0+rocm7.2
    - torchvision == 0.26.0+rocm7.2
  - ultralytics == 8.4.41
  - conda-forge::opencv == 4.13.0
  - pymodbus == 3.13.0
